const screens=[...document.querySelectorAll('[data-screen]')];
const dotsWrap=document.querySelector('.dots');
let i=0;
const makeDots=()=>{dotsWrap.innerHTML='';screens.forEach((_,idx)=>{const d=document.createElement('div');d.className='dot'+(idx===i?' active':'');dotsWrap.appendChild(d);});};
const render=()=>{screens.forEach((s,idx)=>s.classList.toggle('active',idx===i));makeDots();};
const next=()=>{i=Math.min(i+1,screens.length-1);render();};
const prev=()=>{i=Math.max(i-1,0);render();};
document.querySelectorAll('[data-next]').forEach(b=>b.addEventListener('click',next));
document.querySelectorAll('[data-prev]').forEach(b=>b.addEventListener('click',prev));
document.querySelectorAll('[data-reset]').forEach(b=>b.addEventListener('click',()=>{i=0;render();}));
render();
